# problem id (it is used for the name of output html file)
id = "A"

# pato to a statement, output params
statements_info = [
    "./statement/statement_ja.md",
    "./statement/statement_en.md",
]
params_path = "./tests/constraints.hpp"

# write constraints
[constraints]
    MIN_AB = 1
    MAX_AB = 1_000_000_000
    MIN_T = 1
    MAX_T = 100_000
