# problem id (it is used for the name of output html file)
id = "A"

# pato to statements
statements_path = [
    ["./statement/statement_ja.md", "ja"],
    ["./statement/statement_en.md", "en"],
]

# output params
params_path = "./tests/constraints.hpp"

# write constraints
[constraints]
    MIN_AB = 1
    MAX_AB = 1_000_000_000
    MIN_T = 1
    MAX_T = 100_000
